[phases.setup]
nixPkgs = ["python39", "postgresql"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt && pip install gunicorn"]

[phases.build]
cmds = ["cd backend && python manage.py collectstatic --noinput"]

[start]
cmd = "bash start.sh"
