[phases.setup]
nixPkgs = ["python39", "postgresql"]
nixLibs = ["python39Packages.pip"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["cd backend && python manage.py collectstatic --noinput"]

[start]
cmd = "bash start.sh"
