[phases.setup]
nixPkgs = ["python311", "gcc", "pkg-config"]
aptPkgs = ["default-libmysqlclient-dev"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
